### ISSUE TITLE
You are trying to load a weight file containing 116 layers into a model with 107 layers.

### ISSUE THREAD

**Issue by rw86347** [OlafenwaMoses/ImageAI#103]
I have verified the path is good.

imageai==2.0.2

train
-----------
macbook-pro:imageAI rwilson$ cat train.py 
from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("weapons")

model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=12, show_network_summary=True)

pred
----------
macbook-pro:imageAI rwilson$ cat train.py 
from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("weapons")

model_trainer.trainModel(num_objects=2, num_experiments=100, enhance_data=True, batch_size=12, show_network_summary=True)
macbook-pro:imageAI rwilson$ cat custom2.py 
from imageai.Prediction.Custom import CustomImagePrediction
import os

execution_path = os.getcwd()
print("path: "+execution_path)
prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath("resnet50_coco_best_v2.0.1.h5")
prediction.setJsonPath("model_class.json")
prediction.loadModel(num_objects=2)

predictions, probabilities = prediction.predictImage("pistol.jpg", result_count=2)

for eachPrediction, eachProbability in zip(predictions, probabilities):
    print(eachPrediction , " : " , eachProbability)

error
-------------
macbook-pro:imageAI rwilson$ python3 custom2.py 
path: /Users/rwilson/Dropbox/dev/smartai/imageRecognition/imageAI
Traceback (most recent call last):
  File "/anaconda3/lib/python3.5/site-packages/imageai/Prediction/Custom/__init__.py", line 385, in loadModel
    model = ResNet50(model_path=self.modelPath, weights="trained", model_input=image_input, num_classes=self.numObjects)
  File "/anaconda3/lib/python3.5/site-packages/imageai/Prediction/ResNet/resnet50.py", line 111, in ResNet50
    model.load_weights(weights_path)
  File "/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1544, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/anaconda3/lib/python3.5/site-packages/tensorflow/python/keras/engine/saving.py", line 784, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 116 layers into a model with 107 layers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "custom2.py", line 10, in <module>
    prediction.loadModel(num_objects=2)
  File "/anaconda3/lib/python3.5/site-packages/imageai/Prediction/Custom/__init__.py", line 389, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.

**Comment by OlafenwaMoses** [comment]
You were loading the object detection model into **CustomImagePrediction** class, instead of loading your trained model.

**Comment by OlafenwaMoses** [comment]
Ensure you parse in the path to the model generated when you trained ImageAI on your **weapons** dataset, and not the **resnet50_coco_best_v2.0.1.h5** which is for detection.

**Comment by sathiya1926** [comment]
Hi, 

The same issue when I have used the custom trained model in object detection class.

**Comment by aqjw** [comment]
What solution?

**Comment by Rublins** [comment]
python video_object_detection.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "video_object_detection.py", line 9, in <module>
    detector.loadModel()
  File "D:\RUBIN\RESEARCH\Tensorflow1\ImageAI-1.0\imageai\Detection\__init__.py", line 589, in loadModel
    model.load_weights(self.modelPath)
  File "C:\Users\Sathiesh Kumar\AppData\Local\Continuum\anaconda3\envs\retina\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\Sathiesh Kumar\AppData\Local\Continuum\anaconda3\envs\retina\lib\site-packages\keras\engine\saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 107 layers into a model with 116 layers.


Please help me
