### ISSUE TITLE
Issue with the requierements[ImportError: DLL load failed: The specified procedure could not be found.]

### ISSUE THREAD

**Issue by catalinfarte** [OlafenwaMoses/ImageAI#110]
I get the following error:

Traceback (most recent call last):
  File "E:/Pycharm projects/Image recognition/test.py", line 1, in <module>
    from imageai.Prediction import ImagePrediction
  File "E:\Pycharm projects\Image recognition\venv\lib\site-packages\imageai\Prediction\__init__.py", line 2, in <module>
    from tensorflow.python.keras.preprocessing import image
  File "E:\Pycharm projects\Image recognition\venv\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "E:\Pycharm projects\Image recognition\venv\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "E:\Pycharm projects\Image recognition\venv\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "E:\Pycharm projects\Image recognition\venv\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

I've installed all requirements. Any ideas?

Thank you,
Catalin

**Comment by catalinfarte** [comment]
Downgrading protobuf to 3.5.1 fixed the issue.
