### ISSUE TITLE
Got "Unable to open object (bad symbol table node signature)" error  when running "video analyzer" example

### ISSUE THREAD

**Issue by GangLiCN** [OlafenwaMoses/ImageAI#131]
Hello, 

I'm hitting below error when running "video analyzer" examples:

D:\Dev\Install\Python\packages\AI_learn\imageai\examples>python video_analysis_per_frame.py
Using TensorFlow backend.
2018-12-28 08:52:46.075376: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "video_analysis_per_frame.py", line 52, in <module>
    video_detector.loadModel()
  File "D:\py36\lib\site-packages\imageai\Detection\__init__.py", line 1024, in loadModel
    model.load_weights(self.modelPath)
  File "D:\py36\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "D:\py36\lib\site-packages\keras\engine\saving.py", line 1021, in load_weights_from_hdf5_group
    g = f[name]
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "D:\py36\lib\site-packages\h5py\_hl\group.py", line 262, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: 'Unable to open object (bad symbol table node signature)'

Same error throws when running another example "video_analyzer_per_second.py".

Does this error mean the model file 'yolo.h5' is corrupt and need to download again ?
If this is the case, I suggest that  you can provide checksum values(sha256,sha128,md5,,,etc) 
on the web page for these model files so that users can compare it.

Thanks !

**Comment by GangLiCN** [comment]
The issue had been fixed.

Reason:  model file is corrupt,  I used "aria2c" to dowload the model file but it looks like the download had been not finished yet, reexecuted "aria2c" and finished downloading.

BTW:  md5 of "yolo.h5":
bb28869448aeac2b53ce6f0f43c34d42

sha256 of "yolo.h5":
bcfda0f438f0a3db74a5e99ad9c6cd62e4773efdd6beee5ef13b5ad7cfb994f0
