### ISSUE TITLE
How to custom train with densenet169, 161

### ISSUE THREAD

**Issue by nguyenanhtuan1008** [OlafenwaMoses/ImageAI#145]
I trying to custom train and predict with densenet169.
I did with train process but when I run predict.py I got an error:
ValueError: You are trying to load a weight file containing 242 layers into a model with 338 layers.
code:

from imageai.Prediction.Custom import CustomImagePrediction
import os
execution_path = os.getcwd()
prediction = CustomImagePrediction()
prediction.setModelTypeAsDenseNet169()
prediction.setModelPath(os.path.join(execution_path, "./data/models/model_Densenet16Jan-002_acc-0.497717.h5"))
prediction.setJsonPath(os.path.join(execution_path, "./data/json/model_class.json"))
prediction.loadModel(num_objects=2)
predictions, probabilities = prediction.predictImage(os.path.join(execution_path, path), result_count=1)
for eachPrediction, eachProbability in zip(predictions, probabilities):
            print(eachPrediction + " : " + eachProbability)

Using TensorFlow backend.
Traceback (most recent call last):
  File "/media/tuanna/4TbDATA/2019/01162019/HumanAI/tmodule/Classify/Custom/__init__.py", line 454, in loadModel
    model = DenseNetImageNet169(model_path=self.modelPath, weights="trained", model_input=image_input, classes=self.numObjects)
  File "/media/tuanna/4TbDATA/2019/01162019/HumanAI/tmodule/Classify/DenseNet/densenet.py", line 338, in DenseNetImageNet169
    classes=classes, activation=activation, model_path=model_path)
  File "/media/tuanna/4TbDATA/2019/01162019/HumanAI/tmodule/Classify/DenseNet/densenet.py", line 182, in DenseNet
    model.load_weights(weights_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 1112, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/_impl/keras/engine/topology.py", line 1497, in load_weights_from_hdf5_group
    ' layers.')
ValueError: You are trying to load a weight file containing 242 layers into a model with 338 layers.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/tuanna/4TbDATA/2019/01162019/HumanAI/predict.py", line 32, in <module>
    prediction.loadModel(num_objects=2)
  File "/media/tuanna/4TbDATA/2019/01162019/HumanAI/tmodule/Classify/Custom/__init__.py", line 458, in loadModel
    raise ValueError("You have specified an incorrect path to the DenseNet model file.")
ValueError: You have specified an incorrect path to the DenseNet model file.

**Comment by OlafenwaMoses** [comment]
Hello, the DenseNet implementation provided for training custom model is the **DenseNet121** network. Other variants will be supported in future updates.

**Comment by nguyenanhtuan1008** [comment]
actually, I already did with trained in Densenet169 then got models, but I get the error when I try to predict image from models trained in Densenet169. I try to apply inception v4 also but didn't work. Can you tell me when is next update?

**Comment by OlafenwaMoses** [comment]
Please keep tab on this thread. #8
