### ISSUE TITLE
Custom Model Training Tutorial not training

### ISSUE THREAD

**Issue by david-schweitzer** [OlafenwaMoses/ImageAI#15]
Hi.  I created a dataset folder just as you described.  I have one class, "vehicles," and so I have the train -> vehicle -> images and test -> vehicle -> images setup.

When I run

from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory("vehicles")
model_trainer.trainModel(num_objects=1, num_experiments=100, enhance_data=True, batch_size=32, show_network_summary=True)

I get the following error after Epoch 1 begins

Epoch 1/100
Traceback (most recent call last):
  File "trainer.py", line 14, in <module>
    model_trainer.trainModel(num_objects=1, num_experiments=100, enhance_data=False, batch_size=32, show_network_summary=False)
  File "C:\Users\RDITLDTS\anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 240, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "C:\Users\RDITLDTS\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training.py", line 2172, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "C:\Users\RDITLDTS\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training.py", line 1855, in train_on_batch
    check_batch_axis=True)
  File "C:\Users\RDITLDTS\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training.py", line 1449, in _standardize_user_data
    self._feed_output_shapes)
  File "C:\Users\RDITLDTS\anaconda3\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\training.py", line 283, in _check_loss_and_target_compatibility
    y.shape) + ' while using as loss `categorical_crossentropy`. '
ValueError: You are passing a target array of shape (32, 1) while using as loss `categorical_crossentropy`. `categorical_crossentropy` expects targets to be binary matrices (1s and 0s) of shape (samples, classes). If your targets are integer classes, you can convert them to the expected format via:
```
from keras.utils import to_categorical
y_binary = to_categorical(y_int)
```

Alternatively, you can use the loss function `sparse_categorical_crossentropy` instead, which does expect integer targets.:

How do I fix this?

**Comment by OlafenwaMoses** [comment]
Hello,

ImageAI supports training models for 2 or more classes. Instead of having only vehicles, I will advice you structure your dataset as below:

train-> car ->images
train-> bus ->images
(you can add more)

test-> car ->images
test-> bus ->images
(you can add more)

**Comment by david-schweitzer** [comment]
Works perfectly, thanks!

**Comment by OlafenwaMoses** [comment]
You are welcome.

**Comment by margegaj24** [comment]
Hi, I have the following error. What might be the problem?
![screenshot from 2018-10-25 15-34-52](https://user-images.githubusercontent.com/20701970/47506768-116c1480-d871-11e8-88ab-7675fdf7d894.png)
