### ISSUE TITLE
Prediction training errors

### ISSUE THREAD

**Issue by Gytis123** [OlafenwaMoses/ImageAI#154]
In attempt to train prediction on GPU i get error:

Number of experiments (Epochs) :  3
Epoch 1/3
Traceback (most recent call last):
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\TrainingTestGPU.py", line 13, in <module>
    model_trainer.trainModel(num_objects=10, num_experiments=3, enhance_data=True, batch_size=8, show_network_summary=True)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 249, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 2177, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 176, in fit_generator
    x, y, sample_weight=sample_weight, class_weight=class_weight)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1940, in train_on_batch
    outputs = self.train_function(ins)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\backend.py", line 2986, in __call__
    run_metadata=self.run_metadata)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "C:\Users\navickg\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [4] vs. [0]
	 [[{{node training/Adam/gradients/global_avg_pooling/Mean_grad/floordiv}} = FloorDiv[T=DT_INT32, _class=["loc:@training/Adam/gradients/global_avg_pooling/Mean_grad/truediv"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](training/Adam/gradients/global_avg_pooling/Mean_grad/Shape-2-0-VecPermuteNCHWToNHWC-LayoutOptimizer, training/Adam/gradients/global_avg_pooling/Mean_grad/Maximum)]]
	 [[{{node loss/add_61/_3471}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_39609_loss/add_61", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**Comment by OlafenwaMoses** [comment]
Kindly install the latest version of ImageAI

`pip3 install imageai --upgrade`
