### ISSUE TITLE
Problem to install with conda

### ISSUE THREAD

**Issue by dzyla** [OlafenwaMoses/ImageAI#187]
pip3 install https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
C:\ProgramData\Anaconda3\Scripts\pip3-script.py:6: UserWarning: Unbuilt egg for Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages)
  from pkg_resources import load_entry_point
c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\req\req_install.py:919: UserWarning: Unbuilt egg for Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages)
  self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
Collecting imageai==2.0.2 from https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl
  Downloading https://github.com/OlafenwaMoses/ImageAI/releases/download/2.0.2/imageai-2.0.2-py3-none-any.whl (151kB)
    100% |████████████████████████████████| 153kB 309kB/s
Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2562, in version
    return self._version
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\commands\install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\commands\install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\operations\check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\operations\check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2567, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages))
You are using pip version 10.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

(base) C:\Users\didny>pip3 install imageai-2.0.2-py3-none-any.whl
C:\ProgramData\Anaconda3\Scripts\pip3-script.py:6: UserWarning: Unbuilt egg for Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages)
  from pkg_resources import load_entry_point
c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\req\req_install.py:919: UserWarning: Unbuilt egg for Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages)
  self.satisfied_by = pkg_resources.get_distribution(str(no_marker))
Processing c:\users\didny\imageai-2.0.2-py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2562, in version
    return self._version
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2669, in __getattr__
    raise AttributeError(attr)
AttributeError: _version

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\basecommand.py", line 228, in main
    status = self.run(options, args)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\commands\install.py", line 318, in run
    self._warn_about_conflicts(to_install)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\commands\install.py", line 442, in _warn_about_conflicts
    package_set, _dep_info = check_install_conflicts(to_install)
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\operations\check.py", line 89, in check_install_conflicts
    state = create_package_set_from_installed()
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_internal\operations\check.py", line 39, in create_package_set_from_installed
    retval[name] = PackageDetails(dist.version, dist.requires())
  File "c:\programdata\anaconda3\lib\site-packages\pip-10.0.1-py3.6.egg\pip\_vendor\pkg_resources\__init__.py", line 2567, in version
    raise ValueError(tmpl % self.PKG_INFO, self)
ValueError: ("Missing 'Version:' header and/or METADATA file", Unknown [unknown version] (c:\programdata\anaconda3\lib\site-packages))

Something like this happens. Anyone some ideas?

**Comment by anchu-simplecrm** [comment]
just write pip

**Comment by OlafenwaMoses** [comment]
Now you can install **ImageAI** directly from PIP by running the command below.

`pip3 install imageai`
