### ISSUE TITLE
quick issue

### ISSUE THREAD

**Issue by EdwinMeriaux** [OlafenwaMoses/ImageAI#230]
Hi so I have a quick question if you have a sec.

I ran the training code:
from imageai.Prediction.Custom import ModelTraining

model_trainer = ModelTraining()
model_trainer.setModelTypeAsResNet()
model_trainer.setDataDirectory(r"C:/Users/edwin/Downloads/aiimages")
model_trainer.trainModel(num_objects=2, num_experiments=10, enhance_data=True, batch_size=32, show_network_summary=True)

I am given the error:
Traceback (most recent call last):

  File "<ipython-input-11-0d478a49042f>", line 1, in <module>
    runfile('C:/Users/edwin/Desktop/keylogger/aitrainer.py', wdir='C:/Users/edwin/Desktop/keylogger')

  File "C:\Users\edwin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\edwin\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/edwin/Desktop/keylogger/aitrainer.py", line 6, in <module>
    model_trainer.trainModel(num_objects=2, num_experiments=10, enhance_data=True, batch_size=32, show_network_summary=True)

  File "C:\Users\edwin\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 249, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])

  File "C:\Users\edwin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)

  File "C:\Users\edwin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 225, in model_iteration
    mode='test')

  File "C:\Users\edwin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 208, in model_iteration
    aggregator.finalize()

  File "C:\Users\edwin\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training_utils.py", line 108, in finalize
    self.results[0] /= self.num_samples_or_steps

IndexError: list index out of range

would you know why?

**Comment by OlafenwaMoses** [comment]
How many images are in your train and test folders per class?
