### ISSUE TITLE
master/examples/custom_object_detection.py

### ISSUE THREAD

**Issue by justaskumelis** [OlafenwaMoses/ImageAI#25]
When trying to process image with possible stop sign in it this error occurs, I think there is issue with detectCustomObjectsFromImage functions object name "stop sign", I think error occurs, because object name consists of two words.

```
Traceback (most recent call last):
  File "C:\Program Files\Python35\lib\site-packages\imageai\Detection\__init__.py", line 430, in detectCustomObjectsFromImage
    if (custom_objects[check_name] == "invalid"):
KeyError: 'stop sign'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\justa\Desktop\ObjectDetection project\detect.py", line 16, in <module>
    detections = detector.detectCustomObjectsFromImage(custom_objects=custom_objects, input_image=os.path.join(execution_path , "image3.jpg"), output_image_path=os.path.join(execution_path , "image3custom.jpg"))
  File "C:\Program Files\Python35\lib\site-packages\imageai\Detection\__init__.py", line 480, in detectCustomObjectsFromImage
    "Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

```

**Comment by OlafenwaMoses** [comment]
Thank you very much for bringing my notice to this. It will be fixed in next version. The next version of ImageAI will be available latest 2 weeks from now.

**Comment by OlafenwaMoses** [comment]
This has been solved. Thank you once again.

**Comment by Kanagachidambaresan** [comment]
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 


This is the error what i get., Please guide me further

**Comment by fninsiima** [comment]
@Kanagachidambaresan It's hard to decipher what the problem is if you post the Error alone. Maybe you can open a new issue, describe the problem in detail, and post the traceback (not just the error alone).
If it's long, just copy and paste it in a log.txt file, and then upload.

**Comment by hariprasadk51** [comment]
How can apply it to a video?

**Comment by hariprasadk51** [comment]
How can we apply it to a video?

**Comment by OlafenwaMoses** [comment]
Visit the tutorials linked below.

https://heartbeat.fritz.ai/detecting-objects-in-videos-and-camera-feeds-using-keras-opencv-and-imageai-c869fe1ebcdb

https://heartbeat.fritz.ai/analyze-and-visualize-detected-video-objects-using-keras-and-imageai-d84c99b0ae8e
