### ISSUE TITLE
Resource exhausted: OOM when allocating tensor

### ISSUE THREAD

**Issue by addriumruss** [OlafenwaMoses/ImageAI#255]
2019-07-25 21:40:47.031911: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555721500 next 2652 of size 256
2019-07-25 21:40:47.033861: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555721600 next 2638 of size 256
2019-07-25 21:40:47.035784: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555721700 next 2639 of size 256
2019-07-25 21:40:47.037577: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555721800 next 2640 of size 256
2019-07-25 21:40:47.039395: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555721900 next 2642 of size 6195200
2019-07-25 21:40:47.042732: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 0000000555D0A100 next 1434 of size 6195200
2019-07-25 21:40:47.044635: I tensorflow/core/common_runtime/bfc_allocator.cc:800] InUse at 00000005562F2900 next 18446744073709551615 of size 8577536
2019-07-25 21:40:47.048228: I tensorflow/core/common_runtime/bfc_allocator.cc:809]      Summary of in-use Chunks by size:
2019-07-25 21:40:47.049485: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1172 Chunks of size 256 totalling 293.0KiB
2019-07-25 21:40:47.050768: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 205 Chunks of size 512 totalling 102.5KiB
2019-07-25 21:40:47.052005: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 4 Chunks of size 768 totalling 3.0KiB
2019-07-25 21:40:47.053428: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 397 Chunks of size 1024 totalling 397.0KiB
2019-07-25 21:40:47.058433: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 5 Chunks of size 1280 totalling 6.3KiB
2019-07-25 21:40:47.059754: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 5 Chunks of size 1536 totalling 7.5KiB
2019-07-25 21:40:47.061187: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 3 Chunks of size 1792 totalling 5.3KiB
2019-07-25 21:40:47.062440: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 269 Chunks of size 2048 totalling 538.0KiB
2019-07-25 21:40:47.065203: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 2304 totalling 2.3KiB
2019-07-25 21:40:47.067011: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 2560 totalling 2.5KiB
2019-07-25 21:40:47.068955: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 2816 totalling 2.8KiB
2019-07-25 21:40:47.070712: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 3328 totalling 3.3KiB
2019-07-25 21:40:47.072582: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 3584 totalling 3.5KiB
2019-07-25 21:40:47.074234: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 3840 totalling 3.8KiB
2019-07-25 21:40:47.076052: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 170 Chunks of size 4096 totalling 680.0KiB
2019-07-25 21:40:47.077708: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 4 Chunks of size 4608 totalling 18.0KiB
2019-07-25 21:40:47.079577: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 5632 totalling 5.5KiB
2019-07-25 21:40:47.087578: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 2 Chunks of size 6912 totalling 13.5KiB
2019-07-25 21:40:47.088799: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 92 Chunks of size 8192 totalling 736.0KiB
2019-07-25 21:40:47.090023: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 9216 totalling 9.0KiB
2019-07-25 21:40:47.091241: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 9472 totalling 9.3KiB
2019-07-25 21:40:47.092580: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 10240 totalling 10.0KiB
2019-07-25 21:40:47.093823: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 12032 totalling 11.8KiB
2019-07-25 21:40:47.095072: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 12544 totalling 12.3KiB
2019-07-25 21:40:47.096506: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 6 Chunks of size 16384 totalling 96.0KiB
2019-07-25 21:40:47.098524: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 5 Chunks of size 24576 totalling 120.0KiB
2019-07-25 21:40:47.099846: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 5 Chunks of size 37632 totalling 183.8KiB
2019-07-25 21:40:47.101252: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 43520 totalling 42.5KiB
2019-07-25 21:40:47.102543: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 33 Chunks of size 65536 totalling 2.06MiB
2019-07-25 21:40:47.103769: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 6 Chunks of size 131072 totalling 768.0KiB
2019-07-25 21:40:47.105039: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 15 Chunks of size 147456 totalling 2.11MiB
2019-07-25 21:40:47.106209: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 180224 totalling 176.0KiB
2019-07-25 21:40:47.107784: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 37 Chunks of size 262144 totalling 9.25MiB
2019-07-25 21:40:47.109189: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 10 Chunks of size 524288 totalling 5.00MiB
2019-07-25 21:40:47.110421: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 20 Chunks of size 589824 totalling 11.25MiB
2019-07-25 21:40:47.112381: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 786432 totalling 768.0KiB
2019-07-25 21:40:47.116990: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 819200 totalling 800.0KiB
2019-07-25 21:40:47.118229: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 54 Chunks of size 1048576 totalling 54.00MiB
2019-07-25 21:40:47.119485: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 1118208 totalling 1.07MiB
2019-07-25 21:40:47.120830: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 1474560 totalling 1.41MiB
2019-07-25 21:40:47.122065: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 20 Chunks of size 1605632 totalling 30.63MiB
2019-07-25 21:40:47.123404: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 1613824 totalling 1.54MiB
2019-07-25 21:40:47.124687: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 11 Chunks of size 2097152 totalling 22.00MiB
2019-07-25 21:40:47.126013: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 30 Chunks of size 2359296 totalling 67.50MiB
2019-07-25 21:40:47.127286: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 3192832 totalling 3.04MiB
2019-07-25 21:40:47.128540: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 23 Chunks of size 3211264 totalling 70.44MiB
2019-07-25 21:40:47.129986: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 4018176 totalling 3.83MiB
2019-07-25 21:40:47.133259: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 22 Chunks of size 4194304 totalling 88.00MiB
2019-07-25 21:40:47.135193: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 4218880 totalling 4.02MiB
2019-07-25 21:40:47.137071: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 4800512 totalling 4.58MiB
2019-07-25 21:40:47.138904: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 4816896 totalling 4.59MiB
2019-07-25 21:40:47.140630: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 5439488 totalling 5.19MiB
2019-07-25 21:40:47.142434: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 6194176 totalling 5.91MiB
2019-07-25 21:40:47.144234: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 16 Chunks of size 6195200 totalling 94.53MiB
2019-07-25 21:40:47.147045: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 8 Chunks of size 6422528 totalling 49.00MiB
2019-07-25 21:40:47.149438: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 7168512 totalling 6.84MiB
2019-07-25 21:40:47.155044: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 7667712 totalling 7.31MiB
2019-07-25 21:40:47.157025: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 7749632 totalling 7.39MiB
2019-07-25 21:40:47.158952: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 8011776 totalling 7.64MiB
2019-07-25 21:40:47.160915: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 8030208 totalling 7.66MiB
2019-07-25 21:40:47.162859: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 5 Chunks of size 8388608 totalling 40.00MiB
2019-07-25 21:40:47.165491: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 8577536 totalling 8.18MiB
2019-07-25 21:40:47.167284: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 8658688 totalling 8.26MiB
2019-07-25 21:40:47.170197: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 12 Chunks of size 9437184 totalling 108.00MiB
2019-07-25 21:40:47.172532: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 9633792 totalling 9.19MiB
2019-07-25 21:40:47.174584: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 10813440 totalling 10.31MiB
2019-07-25 21:40:47.176521: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 11475968 totalling 10.94MiB
2019-07-25 21:40:47.178417: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 12388352 totalling 11.81MiB
2019-07-25 21:40:47.183905: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 12793856 totalling 12.20MiB
2019-07-25 21:40:47.185266: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 12 Chunks of size 12845056 totalling 147.00MiB
2019-07-25 21:40:47.186636: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 15178752 totalling 14.48MiB
2019-07-25 21:40:47.187936: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 21569536 totalling 20.57MiB
2019-07-25 21:40:47.189285: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 9 Chunks of size 24780800 totalling 212.70MiB
2019-07-25 21:40:47.190673: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 3 Chunks of size 25690112 totalling 73.50MiB
2019-07-25 21:40:47.192041: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 26041856 totalling 24.83MiB
2019-07-25 21:40:47.193375: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 27893760 totalling 26.60MiB
2019-07-25 21:40:47.195063: I tensorflow/core/common_runtime/bfc_allocator.cc:812] 1 Chunks of size 39387136 totalling 37.56MiB
2019-07-25 21:40:47.196474: I tensorflow/core/common_runtime/bfc_allocator.cc:816] Sum Total of in-use chunks: 1.33GiB
2019-07-25 21:40:47.199219: I tensorflow/core/common_runtime/bfc_allocator.cc:818] total_region_allocated_bytes_: 1427245824 memory_limit_: 1427245875 available byte
s: 51 curr_region_allocation_bytes_: 2854492160
2019-07-25 21:40:47.202207: I tensorflow/core/common_runtime/bfc_allocator.cc:824] Stats:
Limit:                  1427245875
InUse:                  1425659136
MaxInUse:               1427237632
NumAllocs:                    5635
MaxAllocSize:            622952448

2019-07-25 21:40:47.205196: W tensorflow/core/common_runtime/bfc_allocator.cc:319] **********************************************************************************
******************
2019-07-25 21:40:47.207073: W tensorflow/core/framework/op_kernel.cc:1502] OP_REQUIRES failed at conv_ops.cc:486 : Resource exhausted: OOM when allocating tensor wit
h shape[8,256,14,14] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "E:/PyCharmProjects/ai/bicycle-training/start.py", line 16, in <module>
    model_trainer.trainModel(num_objects=3, num_experiments=100, enhance_data=True, batch_size=8, show_network_summary=True, save_full_model=True)
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 309, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1433, in fit_generator
    steps_name='steps_per_epoch')
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\training_generator.py", line 264, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1175, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\keras\backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "D:\AI\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[8,1024,14,14] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/gradients/zeros_114}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[loss/mul/_1979]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[8,1024,14,14] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node training/gradients/zeros_114}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Process finished with exit code 1

**Comment by addriumruss** [comment]
how to fix this problem?  
my gpu is NVIDIA GeForce MX150. 
Thanks!

**Comment by OlafenwaMoses** [comment]
Kindly refer to this discussion.

https://github.com/tensorflow/models/issues/1993
