### ISSUE TITLE
failed to run

### ISSUE THREAD

**Issue by guoxinzhan** [OlafenwaMoses/ImageAI#272]
environment：2*RTX2070
                        tensorflow-gpu=1.14/tensorflow-gpu=2.0.0-dev20190622
                        cuda 10.0 cudnn7

code：
from imageai.Prediction.Custom import ModelTraining
model_trainer = ModelTraining()
model_trainer.setModelTypeAsInceptionV3()
model_trainer.setDataDirectory("/home/data/depth")
model_trainer.trainModel(num_objects=3, num_experiments=100, enhance_data=True, batch_size=24, show_network_summary=True)

ERRO:
2019-08-06 09:17:55.176781: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d/Conv2D}}]]
         [[batch_normalization_15/cond/else/_391/FusedBatchNormV3/_1554]]
2019-08-06 09:17:55.180221: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv2d/Conv2D}}]]
Traceback (most recent call last):
  File "AI.py", line 5, in <module>
    model_trainer.trainModel(num_objects=3, num_experiments=100, enhance_data=True, batch_size=24, show_network_summary=True)
  File "/usr/local/lib/python3.6/dist-packages/imageai/Prediction/Custom/__init__.py", line 310, in trainModel
    validation_steps=int(num_test / batch_size), callbacks=[checkpoint, lr_scheduler])
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 1197, in fit_generator
    steps_name='steps_per_epoch')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/training.py", line 939, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py", line 3483, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 583, in __call__
    return self._call_flat(args, self.captured_inputs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 685, in _call_flat
    outputs = self._inference_function.call(ctx, args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/function.py", line 454, in call
    ctx=ctx)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d/Conv2D (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1694) ]]
         [[batch_normalization_15/cond/else/_391/FusedBatchNormV3/_1554]]
  (1) Unknown:  Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[node conv2d/Conv2D (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1694) ]]
0 successful operations.
0 derived errors ignored. [Op:__inference_keras_scratch_graph_49085]

Function call stack:
keras_scratch_graph -> keras_scratch_graph

Any help is much appreciated.

**Comment by OlafenwaMoses** [comment]
Kindly install Tensorflow-GPU 1.13.1

`pip3 install tensorflow-gpu==1.13.1`
