### ISSUE TITLE
Crash (Killed signal) after Epoch 1/200

### ISSUE THREAD

**Issue by baddth** [OlafenwaMoses/ImageAI#299]
Hi there,

Thanks for the super useful library. I can run almost all samples except this one when I tried to train my custom models. I tried on both my windows and mac machine but no luck.

Code: using the custom training example
```
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="Baddth")
trainer.setTrainConfig(object_names_array=["Baddth"], batch_size=4, num_experiments=200, train_from_pretrained_model="../yolo.h5")
trainer.trainModel()
```

Behavior: Always received Killed signal (crash) after Epoch 1/200
I already tried installing tensorflow 1.13.1. But it doesn't seem to help.

My machine might not be using GPU right now tho. Not sure if that's related?
Suggestion on how to solve this issue would be appreciated.

Python 3.5.1
imageai              2.1.3 
opencv-python        4.1.0.25
tensorboard          1.13.1  
tensorflow           1.13.1  
tensorflow-estimator 1.13.0  
tensorflow-gpu       1.13.1 

```
root@70c0ce95b9ba:/mydrive/custom-train# python ./custom_train.py 
Using TensorFlow backend.
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Generating anchor boxes for training images and annotation...
Average IOU for 9 anchors: 0.79
Anchor Boxes generated.
Detection configuration saved in  Baddth/json/detection_config.json
Some labels have no annotations! Please revise the list of labels in your configuration.
Training on: 	None
Training with Batch Size:  4
Number of Experiments:  200
Traceback (most recent call last):
  File "./custom_train.py", line 9, in <module>
    trainer.trainModel()
  File "/usr/local/lib/python3.5/site-packages/imageai/Detection/Custom/__init__.py", line 227, in trainModel
    norm=normalize
  File "/usr/local/lib/python3.5/site-packages/imageai/Detection/Custom/generator.py", line 36, in __init__
    if shuffle: np.random.shuffle(self.instances)
  File "mtrand.pyx", line 4065, in numpy.random.mtrand.RandomState.shuffle
TypeError: object of type 'NoneType' has no len()
root@70c0ce95b9ba:/mydrive/custom-train# python ./custom_train.py 
Using TensorFlow backend.
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Generating anchor boxes for training images and annotation...
Average IOU for 9 anchors: 0.81
Anchor Boxes generated.
Detection configuration saved in  Baddth/json/detection_config.json
Some labels have no annotations! Please revise the list of labels in your configuration.
Training on: 	None
Training with Batch Size:  4
Number of Experiments:  200
Traceback (most recent call last):
  File "./custom_train.py", line 9, in <module>
    trainer.trainModel()
  File "/usr/local/lib/python3.5/site-packages/imageai/Detection/Custom/__init__.py", line 227, in trainModel
    norm=normalize
  File "/usr/local/lib/python3.5/site-packages/imageai/Detection/Custom/generator.py", line 36, in __init__
    if shuffle: np.random.shuffle(self.instances)
  File "mtrand.pyx", line 4065, in numpy.random.mtrand.RandomState.shuffle
TypeError: object of type 'NoneType' has no len()
root@70c0ce95b9ba:/mydrive/custom-train# python ./custom_train.py 
Using TensorFlow backend.
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Generating anchor boxes for training images and annotation...
Average IOU for 9 anchors: 0.81
Anchor Boxes generated.
Detection configuration saved in  Baddth/json/detection_config.json
Training on: 	['Baddth']
Training with Batch Size:  4
Number of Experiments:  200
WARNING:tensorflow:From /usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.5/site-packages/imageai/Detection/Custom/yolo.py:24: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Training with transfer learning from pretrained Model
/usr/local/lib/python3.5/site-packages/keras/callbacks.py:1065: UserWarning: `epsilon` argument is deprecated and will be removed, use `min_delta` instead.
  warnings.warn('`epsilon` argument is deprecated and '
WARNING:tensorflow:From /usr/local/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
Epoch 1/200
Killed
```

**Comment by acleitao76** [comment]
what mac you have? (just for curious) I thought I couldnt train on my macbook pro because i don't have nvidia

**Comment by OlafenwaMoses** [comment]
For this error, 
`
Some labels have no annotations! Please revise the list of labels in your configuration
Training on: 	None
Training with Batch Size:  4
Number of Experiments:  200`
 there is a chance you have missing data in your dataset

**Comment by OlafenwaMoses** [comment]
I will investigate further what might be the cause of the issue. However, have you tried training with Google Colab?

https://colab.research.google.com/

**Comment by Meulen92** [comment]
What is the memory usage on your MacBook? Please try to run on a lower batch_size, 2 for example, and see if it survives the first epoch.

I know the YoloV3 training is particularly hungry for memory. For example, training with a batch size of 6 almost completely uses up my 8GB of memory.

**Comment by acleitao76** [comment]
@Meulen92 do you have the code for training using cpu insteado of gpu?  Does this code still applies?
from imageai.Detection.Custom import DetectionModelTrainer
trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="/content/drive/My Drive/Colab Notebooks/bib2019-08-19")
trainer.setTrainConfig(object_names_array=["bibnumber"], batch_size=4, num_experiments=15, train_from_pretrained_model="/content/drive/My Drive/Colab Notebooks/bib2019-08-19/pretrained-yolov3.h5")
trainer.trainModel()
print ('finish')

as I'm having trouble on getting a gpu I'm thinking about putting 16gb on a linux vaio laptop I have at home and leave it running over a month for training a model with a 10k images dataset

**Comment by baddth** [comment]
Hi all, thanks everyone for being super supportive! I wanted to give an update on the finding and latest status here.

1) In short, training a new custom model is quite a resource consuming process. Without GPU, trainModel() seems to behave very abnormally -- It halted on Windows Docker and freeze on OSX Docker.  Not 100% verified but I might be able to reproduce this on small training dataset (with or without transfer-learning) as well. (First hope it'll be able to train something with smaller dataset)

2) Using Colab helps passing epoch 1/200. (with switching runtime mode to GPU and pip install tensorflow-gpu 1.13.1). However, if you run the code too much, CoLab'll stop giving GPU to the runtime. So, that's a little tricky part. In my case, it runs until epoch 4/200 then suddenly stopped running. Not sure if it finished successfully, or somethings happen in between.

I received a series of .h5 in the model folder tho. However, I tried using this in detectCustomObjectsFromVideo function but received the error below.  I wonder if this is because the training process failed. Or I didn't use detectCustomObjectsFromVideo correctly?

```
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "video-obj-custom.py", line 10, in <module>
    detector.loadModel()
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\imageai\Detection\__init__.py", line 1055, in loadModel
    model.load_weights(self.modelPath)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
    assign_op = x.assign(assign_placeholder)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\variables.py", line 1762, in assign
    name=name)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\state_ops.py", line 223, in assign
    validate_shape=validate_shape)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 67, in assign
    use_locking=use_locking, name=name)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
    op_def=op_def)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
    control_input_ops)
  File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].
```.

**Comment by baddth** [comment]
> what mac you have? (just for curious) I thought I couldnt train on my macbook pro because i don't have nvidia

My Macbook is Pro 15" (touchbar model). I realized afterward that OSX might not be able to run tensorflow GPU at all. So, it's actually not the right option to run the training code.

**Comment by Meulen92** [comment]
> @Meulen92 do you have the code for training using cpu insteado of gpu? Does this code still applies?
> 
> ```
> from imageai.Detection.Custom import DetectionModelTrainer
> trainer = DetectionModelTrainer()
> trainer.setModelTypeAsYOLOv3()
> trainer.setDataDirectory(data_directory="/content/drive/My Drive/Colab Notebooks/bib2019-08-19")
> trainer.setTrainConfig(object_names_array=["bibnumber"], batch_size=4, num_experiments=15, train_from_pretrained_model="/content/drive/My Drive/Colab Notebooks/bib2019-08-19/pretrained-yolov3.h5")
> trainer.trainModel()
> print ('finish')
> ```
> 
> as I'm having trouble on getting a gpu I'm thinking about putting 16gb on a linux vaio laptop I have at home and leave it running over a month for training a model with a 10k images dataset

As for the code to force it to run on CPU:

`config = tf.ConfigProto(
        device_count = {'GPU': 0}
    )
session = tf.Session(config=config)`

**Comment by OlafenwaMoses** [comment]
> Hi all, thanks everyone for being super supportive! I wanted to give an update on the finding and latest status here.
> 
> 1. In short, training a new custom model is quite a resource consuming process. Without GPU, trainModel() seems to behave very abnormally -- It halted on Windows Docker and freeze on OSX Docker.  Not 100% verified but I might be able to reproduce this on small training dataset (with or without transfer-learning). First hope it'll be able to train something with smaller dataset even without GPU. (So far, couldn't get the code to run with CPU version. Hopefully I didn't misunderstand anything)
> 2. Using Colab helps passing epoch 1/200. (with switching runtime mode to GPU and pip install tensorflow-gpu 1.13.1). However, if you run the code too much, CoLab'll stop giving GPU to the runtime. So, that's a little tricky part. In my case, it runs until epoch 4/200. Then it suddenly stopped running itself. Not sure if it finished successfully, or somethings happen in between.
> 
> I received a series of .h5 in the model folder tho. However, I tried using this in detectCustomObjectsFromVideo function but received the error below. I wonder if this is because the training process failed. Or I didn't use detectCustomObjectsFromVideo correctly?
> 
> detectCustomObjectsFromVideo :
> 
> ```
> from imageai.Detection import VideoObjectDetection
> import os
> 
> execution_path = os.getcwd()
> 
> detector = VideoObjectDetection()
> detector.setModelTypeAsYOLOv3()
> detector.setModelPath( os.path.join(execution_path , "../detection_model-ex-11--loss-10.00.h5"))
> #detector.setModelPath( os.path.join(execution_path , "../models/baddth/detection_model-ex-20--loss-4.88.h5"))
> detector.loadModel()
> 
> custom = detector.CustomObjects(person=True)
> 
> video_path = detector.detectCustomObjectsFromVideo(custom_objects=custom, input_file_path=os.path.join(execution_path, "cake2.mp4"),
>                                 output_file_path=os.path.join(execution_path, "cake2_custom.mp4")
>                                 , frames_per_second=29, log_progress=True)
> print(video_path)
> ```
> 
> ERROR:
> 
> ```
> Colocations handled automatically by placer.
> Traceback (most recent call last):
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1659, in _create_c_op
>     c_op = c_api.TF_FinishOperation(op_desc)
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "video-obj-custom.py", line 10, in <module>
>     detector.loadModel()
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\imageai\Detection\__init__.py", line 1055, in loadModel
>     model.load_weights(self.modelPath)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\engine\network.py", line 1166, in load_weights
>     f, self.layers, reshape=reshape)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\engine\saving.py", line 1058, in load_weights_from_hdf5_group
>     K.batch_set_value(weight_value_tuples)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\keras\backend\tensorflow_backend.py", line 2465, in batch_set_value
>     assign_op = x.assign(assign_placeholder)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\variables.py", line 1762, in assign
>     name=name)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\state_ops.py", line 223, in assign
>     validate_shape=validate_shape)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\ops\gen_state_ops.py", line 67, in assign
>     use_locking=use_locking, name=name)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
>     op_def=op_def)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 3300, in create_op
>     op_def=op_def)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1823, in __init__
>     control_input_ops)
>   File "C:\Users\baddt\Desktop\docker\mydrive\imageai\env\lib\site-packages\tensorflow\python\framework\ops.py", line 1662, in _create_c_op
>     raise ValueError(str(e))
> ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].
> ```. 
> ```

@baddth Thank you for this detailed evaluation. Let me address the issues raised.

- Training of custom models _(prediction and detection)_ requires **GPU acceleration**, which for now is using **NVIDIA GPU**s. Google Colab provide a NVIDIA **Tesla T4** GPU which is why it can run your model training many times faster than the CPU. 
- **ImageAI** primarily implements deep learning algorithms which require high compute (**GPUs**) for training, and same for real-time inference. You can read more on deep learning and GPUs here.

- In your colab training, I could observe from your model file name that your training actually reached **20 experiments ** `detection_model-ex-20-....`, which means it was still training. If your Colab shows disconnected, all you need to do to see the latest state of your training is to click the **Connect** tab on the top right and the Notebook will update.

- In your detection code, you were using the wrong class for your custom model. The class you need is the `from imageai.Detection.Custom  import  CustomVideoObjectDetection`. See the link below for the full code sample. Ensure you parse in your trained model path and the generated **detection_config.json** file path.

https://github.com/OlafenwaMoses/ImageAI/blob/master/imageai/Detection/Custom/CUSTOMVIDEODETECTION.md#videodetection
