### ISSUE TITLE
sytem can not find route to annotation folder

### ISSUE THREAD

**Issue by OraculoML** [OlafenwaMoses/ImageAI#304]
Generating anchor boxes for training images and annotation...
Traceback (most recent call last):
  File "start.py", line 6, in <module>
    trainer.setTrainConfig(object_names_array=["hololens"], batch_size=4, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\imageai\Detection\Custom\__init__.py", line 161, in setTrainConfig
    self.__train_cache_file, self.__model_labels)
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\imageai\Detection\Custom\gen_anchors.py", line 81, in generateAnchors
    model_labels
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\imageai\Detection\Custom\voc.py", line 15, in parse_voc_annotation
    for ann in sorted(os.listdir(ann_dir)):
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'hololens\\train/annotations/'

**Comment by OlafenwaMoses** [comment]
The folder `hololens/train/annotations/` appears to be missing. Ensure the dataset folder is properly arranged.

**Comment by OraculoML** [comment]
I am having other issues. I have uninstalled Keras and reinstalled but now it says "module now found"...  I resolved that i think , now i am getting this:

Traceback (most recent call last):
  File "start.py", line 1, in <module>
    from imageai.Detection.Custom import DetectionModelTrainer
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\imageai\Detection\__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\Admin\Anaconda3\envs\TensorGPU\lib\site-packages\keras\backend\tensorflow_backend.py", line 6, in <module>
    from tensorflow.python.framework import ops as tf_ops
ImportError: cannot import name 'ops'

**Comment by rola93** [comment]
Looks related to #303 take a look at the discussion and see if suggested solution applies to your case.

It is for sure a bug.

**Comment by rola93** [comment]
Hey! I think #336 should have solved the initial issue. 

> I am having other issues. I have uninstalled Keras and reinstalled but now it says "module now found"... I resolved that i think , now i am getting this:

This second issue looks like a problem with your keras/tensorflow installation.

You should open a new issue in that case, just to get things clear.
