### ISSUE TITLE
ValueError: you are trying to load a weight file containing 00 layers into a model with 147 layers.

### ISSUE THREAD

**Issue by Odor98** [OlafenwaMoses/ImageAI#31]
Hello!
First, thank you for your great job

i'm trying to run the object_detection.py on Ubuntu 14.04 ( virtual box ) but getting an error
The libraries and their versions are up to date:

* python 3.4.3
* tensorflow 1.9.0
* numpy 1.14.5
* scipy 1.1.0
* opencv_python 3.4.1.15
* pillow 5.2.0
* matplotlib 2.2.2
* h5py 2.8.0
* keras 2.2.0

Using TensorFlow backend.
2018-07-16 15:12:06.173943: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "./object_detection.py", line 10, in <module>
    detector.loadModel()
  File "/root/ImageAI/imageai/Detection/__init__.py", line 190, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/saving.py", line 901, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 24 layers into a model with 147 layers.

Thank you for reading through.

**Comment by OlafenwaMoses** [comment]
Hello,

You are experiencing this error because you set the wrong type of model for the file you downloaded. Ensure you set the correct model type for the model file you are trying to load.

In addition, please post your code in the comments here so that I can review it.

**Comment by Odor98** [comment]
type of model means resnet, yolo, yolo-tiny? 
I've tried them all


#!/usr/bin/env python3
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image3.jpg"), output_image_path=os.path.join(execution_path , "image3new.jpg"), minimum_percentage_probability=30)

for eachObject in detections:
    print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
    print("--------------------------------")

RRRRRResult

root@odor98-VirtualBox:~/ImageAI# ./object_detection.py 
Using TensorFlow backend.
2018-07-16 15:46:34.165950: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "./object_detection.py", line 10, in <module>
    detector.loadModel()
  File "/root/ImageAI/imageai/Detection/__init__.py", line 190, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/saving.py", line 901, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 116 layers into a model with 147 layers.

=====================================================
#!/usr/bin/env python3
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image3.jpg"), output_image_path=os.path.join(execution_path , "image3new.jpg"), minimum_percentage_probability=30)

for eachObject in detections:
    print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
    print("--------------------------------")


RRRRRRRResult
root@odor98-VirtualBox:~/ImageAI# ./object_detection.py 
Using TensorFlow backend.
2018-07-16 15:47:45.492264: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "./object_detection.py", line 10, in <module>
    detector.loadModel()
  File "/root/ImageAI/imageai/Detection/__init__.py", line 190, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/network.py", line 1171, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)


==========================================

yolo-tiny

RRRRRREsult

root@odor98-VirtualBox:~/ImageAI# ./object_detection.py 
Using TensorFlow backend.
2018-07-16 15:49:23.235005: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "./object_detection.py", line 10, in <module>
    detector.loadModel()
  File "/root/ImageAI/imageai/Detection/__init__.py", line 190, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/network.py", line 1180, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/saving.py", line 901, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 24 layers into a model with 147 layers.

**Comment by Odor98** [comment]
oh I got it

detector.setModelTypeAsYOLOv3()  <<<
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))

**Comment by OlafenwaMoses** [comment]
In the above code, you tried 3 different options. The 2nd is the correct one and as you can see, it is the only one without the this type of error "ValueError: You are trying to load a weight file containing 116 layers into a model with 147 layers" or  "ValueError: You are trying to load a weight file containing 24 layers into a model with 147 layers".

Please note that you have to install the latest version of ImageAI to use YOLOv3 and TinyYOLOv3.
Go to the repository homepage and find the installation instruction as below.

https://github.com/OlafenwaMoses/ImageAI#installation

 And most importantly:

- when you set your model type as RetinaNet, you must use the model file with name "resnet50_coco_best_v2.0.1.h5"

- when you set your model type as YOLOv3, you must use the model file with name "yolo.h5"

- when you set your model type as TinyYOLOv3, you must use the model file with name "yolo-tiny.h5"

For this error "Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2" that is reported, look into the solutions provided below:

https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u

**Comment by Odor98** [comment]
Actually i didn't solved that tensorflow : AVX2
but i have another error
Is that tensorflow Error??

Setmodel Yolo.h5 

from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath( os.path.join(execution_path , "yolo.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image2.jpg"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30)

for eachObject in detections:
    print(eachObject["name"] , " : ", eachObject["percentage_probability"], " : ", eachObject["box_points"] )
    print("--------------------------------")


================================
Using TensorFlow backend.
2018-07-17 15:26:13.108920: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "object_detection.py", line 9, in <module>
    detector.loadModel()
  File "/root/ImageAI/imageai/Detection/__init__.py", line 190, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/network.py", line 1171, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python3.4/dist-packages/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

Yolo-tiny
======================================================
Using TensorFlow backend.
2018-07-17 15:27:37.525966: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-07-17 15:27:39.867285: W tensorflow/core/framework/allocator.cc:108] Allocation of 18874368 exceeds 10% of system memory.
2018-07-17 15:27:40.034556: W tensorflow/core/framework/allocator.cc:108] Allocation of 18874368 exceeds 10% of system memory.
2018-07-17 15:27:40.084036: W tensorflow/core/framework/allocator.cc:108] Allocation of 18874368 exceeds 10% of system memory.
Traceback (most recent call last):
  File "/root/ImageAI/imageai/Detection/__init__.py", line 401, in detectObjectsFromImage
    image = Image.open(input_image)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/ImageAI/image2.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection.py", line 10, in <module>
    detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image2.jpg"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30)
  File "/root/ImageAI/imageai/Detection/__init__.py", line 517, in detectObjectsFromImage
    raise ValueError("Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 

RetinaNet
========================================
Using TensorFlow backend.
2018-07-17 15:34:13.555521: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
  File "/root/ImageAI/imageai/Detection/__init__.py", line 311, in detectObjectsFromImage
    image = read_image_bgr(input_image)
  File "/root/ImageAI/imageai/Detection/keras_retinanet/utils/image.py", line 29, in read_image_bgr
    image = np.asarray(Image.open(path).convert('RGB'))
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/root/ImageAI/image2.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "object_detection.py", line 10, in <module>
    detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image2.jpg"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30)
  File "/root/ImageAI/imageai/Detection/__init__.py", line 517, in detectObjectsFromImage
    raise ValueError("Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by Odor98** [comment]
i solve my problem 
image file should exist with .py file ..... 

Thanks your help

**Comment by haseeAmarathunga** [comment]
Change 

> detector.setModelTypeAsYOLOv3()
 to 

> detector.setModelTypeAsRetinaNet()

**Comment by pouyx** [comment]
@OlafenwaMoses  I have problem to Run YoloV3 detections on thousands of images and save outputs.
It is my Programm and but that only works for 300 pictures then I get this problem

###################################################
from imageai.Detection.Custom import CustomObjectDetection
import os
import time
import glob 
import numpy as np
from numpy import arange
import sys
from colorama import init 
from termcolor import colored 
detector = CustomObjectDetection()
detector.setModelTypeAsYOLOv3()
detector.setModelPath("Z:\\SHS-test\\Yolov\\Models\\3.Modell\\models\\detection_model-ex-089--loss-0017.766.h5") 
detector.setJsonPath("Z:\\SHS-test\\Yolov\\Models\\3.Modell\\json\\detection_config.json")
detector.loadModel()
i = 0
detections = []
data_list = []
Wahr_list =[]
name_list = []
x = []
y =[]
word = []
for fileNameWithPath in glob.glob('Z:\\FehlerIMG\\Auto-teile\\350image/*.jpg'):
    fileName = fileNameWithPath.replace('Z:\\FehlerIMG\\Auto-teile\\350image\\', "")
    
   
    start=time.time()  

    detections, extracted_objects_array = detector.detectObjectsFromImage(input_image= fileNameWithPath, output_image_path="C:\\pic\\output\\"+ 'detect_'+ fileName, input_type="file", output_type="file", extract_detected_objects=True)    
    ende=time.time()
    
    
    zeitverlauf = ende-start 
    init()
    print(colored('Dauer der Objektserkennung:', 'green')) 
    print(colored(zeitverlauf, 'green', 'on_red')) 
    print('Anzahl der erkannten Objekte:',len(detections))
    
    for detection, object_path in zip(detections, extracted_objects_array):
    
        All_Data = (detection["name"], " : ", detection["percentage_probability"], " : ", detection["box_points"])
        
        print(colored(All_Data, 'blue')) 
      
        print(object_path)  
        Name = detection["name"]
        Probability =  detection["percentage_probability"]
        
        Box = detection["box_points"]
        wahr = int(Probability)
        
        if wahr > 80.0 and wahr < 90 :
            print('wie gut ist Objektserkennung: good')
        if wahr > 90.0 and wahr < 98 :
            print ('wie gut ist Objektserkennung: very good')
        if wahr > 98.0:
            print('wie gut ist Objektserkennung: Excellent')
       
        replicate = 9
       
        i +=1
        x = arange(1,2)
        with open("output_data" + str(replicate) + ".csv", "a") as out_file:
            for q in range(len(x)):
                out_string = ""
                out_string += str(Name)
                out_string += "," + str(wahr)
                out_string += "," + str(Box)
                out_string += "," + str(fileName)
                out_string += "\n"
                out_file.write(out_string)

#########################################
C:\pic\output\detect_00041_14_025469_1_FG-objects\Number of Company Registration-00000.jpg
wie gut ist Objektserkennung: very good
Dauer der Objektserkennung:
0.1351761817932129
Anzahl der erkannten Objekte: 0
Traceback (most recent call last):

What can i do? Thanks alot
