### ISSUE TITLE
tensorflow backend

### ISSUE THREAD

**Issue by ron028** [OlafenwaMoses/ImageAI#313]
**i am using the following codes:**

from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image1.jpg"), output_image_path=os.path.join(execution_path , "imagenew.jpg"))

for eachObject in detections:
    print(eachObject["name"] , " :   " , eachObject["percentage_probability"] )

**the error I am getting everytime:**

Using TensorFlow backend.
Traceback (most recent call last):
  File "D:/School Files/Thesis/detection/car_detection.py", line 1, in <module>
    from imageai.Detection import ObjectDetection
  File "D:\Program Files\python 3.6\lib\site-packages\imageai\Detection\__init__.py", line 2, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "D:\Program Files\python 3.6\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "D:\Program Files\python 3.6\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "D:\Program Files\python 3.6\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "D:\Program Files\python 3.6\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "D:\Program Files\python 3.6\lib\site-packages\keras\backend\__init__.py", line 1, in <module>
    from .load_backend import epsilon
  File "D:\Program Files\python 3.6\lib\site-packages\keras\backend\load_backend.py", line 89, in <module>
    from .tensorflow_backend import *
  File "D:\Program Files\python 3.6\lib\site-packages\keras\backend\tensorflow_backend.py", line 5, in <module>
    import tensorflow as tf
  File "D:\Program Files\python 3.6\lib\site-packages\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "D:\Program Files\python 3.6\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "D:\Program Files\python 3.6\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "D:\Program Files\python 3.6\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.

Process finished with exit code 1

**how do i Fix this issue? thanks**

**Comment by rola93** [comment]
any news on this? otherwise should be closed cc @OlafenwaMoses

**Comment by OlafenwaMoses** [comment]
Thanks @rola93
