### ISSUE TITLE
conda tensorflow-gpu version conflict

### ISSUE THREAD

**Issue by maxware0715** [OlafenwaMoses/ImageAI#327]
The problem happened when I install tf-gpu by conda instead of tf cpu version. It seems like cudnn mismatch problem and conda provides only 7.3 and 7.6 version. Is there any solution to build appropriate environment by conda?

W0902 04:30:46.757832 140257303783232 deprecation_wrapper.py:119] From /home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:1919: The name tf.nn.fused_batch_norm is deprecated. Please use tf.compat.v1.nn.fused_batch_norm instead.

W0902 04:30:46.759829 140257303783232 deprecation_wrapper.py:119] From /home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3976: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

W0902 04:30:47.864533 140257303783232 deprecation_wrapper.py:119] From /home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/imageai/Detection/keras_retinanet/backend/tensorflow_backend.py:22: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

W0902 04:30:48.388976 140257303783232 deprecation.py:323] From /home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/imageai/Detection/keras_retinanet/backend/tensorflow_backend.py:46: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
2019-09-02 04:30:54.357566: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-09-02 04:30:54.484078: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-09-02 04:30:56.829854: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2019-09-02 04:30:56.831738: E tensorflow/stream_executor/cuda/cuda_dnn.cc:329] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
Traceback (most recent call last):
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/imageai/Detection/__init__.py", line 340, in detectObjectsFromImage
    _, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/keras/engine/training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}}]]
         [[nms/strided_slice_121/_2001]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node conv1/convolution}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "img.py", line 10, in <module>
    detections, objects_path = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "image2.jpg"), output_image_path=os.path.join(execution_path , "image2new.jpg"), minimum_percentage_probability=30, extract_detected_objects=True)
  File "/home/users/tzong_hann/anaconda3/envs/myenv/lib/python3.6/site-packages/imageai/Detection/__init__.py", line 526, in detectObjectsFromImage
    "Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by maxware0715** [comment]
I solve it by install tf-gpu=1.12, rather than 1.13 as mentioned. Could requirement file provide detailed version? It may help someone like me.
