### ISSUE TITLE
ZeroDivisionError Whilst Training

### ISSUE THREAD

**Issue by lclcpg2018** [OlafenwaMoses/ImageAI#345]
Hi! I'm training a custom network to do things...

But I get this error

Traceback (most recent call last):
  File "training.py", line 6, in <module>
    trainer.setTrainConfig(object_names_array=["face"], batch_size=4, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")
  File "//anaconda3/lib/python3.7/site-packages/imageai/Detection/Custom/__init__.py", line 176, in setTrainConfig
    self.__train_cache_file, self.__model_labels)
  File "//anaconda3/lib/python3.7/site-packages/imageai/Detection/Custom/gen_anchors.py", line 89, in generateAnchors
    relative_w = (float(obj['xmax']) - float(obj['xmin']))/image['width']
ZeroDivisionError: float division by zero

Does it have anything to do with my annotations?

**Comment by AdrianNg** [comment]
you can search if you have `<width>0` in your xml file

**Comment by lclcpg2018** [comment]
Thank you so much! Problem solved...
