### ISSUE TITLE
Tensorflow error "ValueError: None values not supported."

### ISSUE THREAD

**Issue by Shellfishgene** [OlafenwaMoses/ImageAI#374]
Hi, I am trying to use the example in the custom model training docs (on the CIFAR-10 dataset). However I get an error:
```
Number of experiments (Epochs) :  100
Epoch 1/100
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 527, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1296, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 286, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 227, in constant
    allow_broadcast=True)
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/user/miniconda3/envs/imageai/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.
```
This seems to be related to this issue: https://github.com/tensorflow/tensorflow/issues/783
Any way around this?

**Comment by rola93** [comment]
Hey! what version of ImageAI/Keras/TensorFlow are you using? Can you share the code that are you using? What is the task you're trying to solve?

Best regards

Rodrigo

**Comment by Shellfishgene** [comment]
I was using TensorFlow 2.0 but saw from the referenced issues it's not supported yet. Seems to work with 1.15, thanks.

**Comment by padmasreenagarajan** [comment]
Hi..Im facing this error when converting Mobilenetv3 onnx file to tensorflow

**File "Python36\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.**

Could u pls guide me in solving this? @Shellfishgene @rola93

**Comment by GarimaZe** [comment]
@padmasreenagarajan  hello! did you solve the error?
and if yes, how?

please revert back, I am stuck in the same. Please help. 

Thank you in advance :)

**Comment by padmasreenagarajan** [comment]
Hello @GarimaZe ,

Yes, I have solved the issue. But, the above issue occurs due to multiple causes.
Please check if u have followed the following version matrix.


**ONNX-TensorFlow version | ONNX version | TensorFlow version

1.2.1 | 1.1.2 (opset 4) | 1.5
1.3.0 | 1.3.0 (opset 8) | 1.13.1
1.5.0 | 1.5.0 (opset 10) | 1.15.0
1.6.0 | 1.6.0 (opset 11) | 1.15.0**

Regards,
Padmasree N.
