### ISSUE TITLE
after train custom model i am getting this error when i am processing video and as well as image also

### ISSUE THREAD

**Issue by DeveloperRachit** [OlafenwaMoses/ImageAI#385]
ValueError: Dimension 0 in both shapes must be equal, but are 1 and 18. Shapes are [1,1,1024,255] and [18,1024,1,1]. for 'Assign_360' (op: 'Assign') with input shapes: [1,1,1024,255], [18,1024,1,1].

**Comment by rola93** [comment]
Can you share your complete stack trace?
Thanks

**Comment by DeveloperRachit** [comment]
okay tell me one thing that has been solved actually i have to train multiple category then what i have to do.
now i train only one category that is fine running well and detecting also.

but when i am going to train multiple categories then it is giving me error as like

====================================================================
Using TensorFlow backend.
Generating anchor boxes for training images and annotation...
9
Average IOU for 9 anchors: 0.67
Anchor Boxes generated.
Detection configuration saved in  ./Dataset/json/detection_config.json
{'Humanhair': 1013}
Some labels have no annotations! Please revise the list of labels in your configuration.
['Humanarm', 'Humanface', 'Humanhair', 'Humanhead']
Training on:    None
Training with Batch Size:  2
Number of Experiments:  4
Traceback (most recent call last):
  File "train.py", line 7, in <module>
    trainer.trainModel()
  File "/usr/local/lib/python3.6/site-packages/imageai/Detection/Custom/__init__.py", line 231, in trainModel
    norm=normalize
  File "/usr/local/lib/python3.6/site-packages/imageai/Detection/Custom/generator.py", line 36, in __init__
    if shuffle: np.random.shuffle(self.instances)
  File "mtrand.pyx", line 4830, in mtrand.RandomState.shuffle
TypeError: object of type 'NoneType' has no len()

**Comment by DeveloperRachit** [comment]
this is my code..,
-------------------------------
from imageai.Detection.Custom import DetectionModelTrainer
import os
trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="./Dataset")
trainer.setTrainConfig(object_names_array=['Humanhair','Humanface','Humanarm','Humanhead'], batch_size=2, num_experiments=4, train_from_pretrained_model="./pretrained-yolov3.h5")
trainer.trainModel()

**Comment by rola93** [comment]
> ```
> if shuffle: np.random.shuffle(self.instances)
> File "mtrand.pyx", line 4830, in mtrand.RandomState.shuffle
> TypeError: object of type 'NoneType' has no len()
> ```

This error is because `self.instances` is None. This is probably because data is not being loaded properly. Check if your directories are ok and your files are actually where they should be. Consider also removing cache folder which may be saving train/validate empty samples from previous runs
