### ISSUE TITLE
raise ValueError("You have specified an incorrect path to the ResNet model file.")

### ISSUE THREAD

**Issue by badzak** [OlafenwaMoses/ImageAI#389]
I have read the custom prediction thread that is closed multiple times as well as additional resources associated with this issue and I have been unable to find the error in my program or my method. Here is my program:
from imageai.Prediction.Custom import CustomImagePrediction
import os
execution_path = os.getcwd()
prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path, "resnet_model_ex-020_acc-0.651714.h5"))
prediction.setJsonPath(os.path.join(execution_path, "model_class.json"))
prediction.loadModel(num_objects=3)
predictions, probabilities = prediction.predictImage(os.path.join(execution_path, "4.jpg"), result_count=5)
for eachPrediction, eachProbability in zip(predictions, probabilities):
    print(eachPrediction , " : " , eachProbability)

**This is the console readout with error:**
runfile('C:/Users/434/Desktop/idenprof/FirstCustomImageRecognition.py', wdir='C:/Users/434/Desktop/idenprof')
Traceback (most recent call last):
  File "<ipython-input-16-d104bc22027b>", line 1, in <module>
    runfile('C:/Users/434/Desktop/idenprof/FirstCustomImageRecognition.py', wdir='C:/Users/434/Desktop/idenprof')
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)
  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/434/Desktop/idenprof/FirstCustomImageRecognition.py", line 17, in <module>
    prediction.loadModel(num_objects=3)
  File "C:\ProgramData\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 389, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.

The model from Train Image Recognition AI with 5 lines of code article works on my computer but is too bulky to run all the way through. I wanted to use this model so that I can change it to recognize weeds. 

This is how my files are saved in the folder on my desktop. 
idenprof_061-0.7933.h5
idenprof_model_class.json
FirstCustomImageRecognition.py

I would appreciate any help with this. Thank you.

**Comment by DrInsanity** [comment]
replace this -> resnet_model_ex-020_acc-0.651714.h5 to idenprof_061-0.7933.h5
and this -> model_class.json to idenprof_model_class.json.
I guess that will solve the problem

**Comment by badzak** [comment]
Thanks for the suggestion but it didn't work. Now I am getting an error that says the following:  File "C:\ProgramData\Anaconda3\lib\site-packages\imageai\Prediction\Custom\__init__.py", line 742, in predictImage
    raise ValueError("You have set a path to an invalid image file.")

ValueError: You have set a path to an invalid image file.

**Comment by kayacancode** [comment]
Has anyone found the solution?

**Comment by badzak** [comment]
No.

**Comment by menavas** [comment]
In my case, my error was in  prediction.loadModel(num_objects=n), n must match the amount of classes in the model

**Comment by jablonsky** [comment]
I have experienced the same issue: 
Traceback (most recent call last):
  File "FirstCustomImageRecognition.py", line 10, in <module>
    prediction.loadModel(num_objects=10)
  File "/home/rafi/anaconda3/envs/ml36/lib/python3.6/site-packages/imageai/Prediction/Custom/__init__.py", line 491, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.
