### ISSUE TITLE
Getting an error while loading the RetinaNet model. Gives the following error :

### ISSUE THREAD

**Issue by vaibhavsethia** [OlafenwaMoses/ImageAI#406]
Traceback (most recent call last):
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/Demo.py", line 9, in <module>
    detector.loadModel()
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/__init__.py", line 190, in loadModel
    model = resnet50_retinanet(num_classes=80)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/resnet.py", line 86, in resnet50_retinanet
    return resnet_retinanet(num_classes=num_classes, backbone='resnet50', inputs=inputs, **kwargs)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/resnet.py", line 80, in resnet_retinanet
    model = retinanet.retinanet_bbox(inputs=inputs, num_classes=num_classes, backbone=resnet, **kwargs)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py", line 347, in retinanet_bbox
    model = retinanet(inputs=inputs, num_classes=num_classes, **kwargs)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py", line 302, in retinanet
    submodels = default_submodels(num_classes, anchor_parameters)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py", line 210, in default_submodels
    ('regression', default_regression_model(anchor_parameters.num_anchors())),
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/imageai/Detection/keras_retinanet/models/retinanet.py", line 125, in default_regression_model
    outputs = keras.layers.Reshape((-1, 4), name='pyramid_regression_reshape')(outputs)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/keras/engine/topology.py", line 554, in __call__
    output = self.call(inputs, **kwargs)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/keras/layers/core.py", line 402, in call
    target_shape = self.compute_output_shape(input_shape)[1:]
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/keras/layers/core.py", line 385, in compute_output_shape
    input_shape[1:], self.target_shape)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/keras/layers/core.py", line 373, in _fix_unknown_dimension
    original = np.prod(input_shape, dtype=int)
  File "<__array_function__ internals>", line 6, in prod
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2911, in prod
    keepdims=keepdims, initial=initial, where=where)
  File "/Users/irateleaf/PycharmProjects/Object_Detection/venv/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by Duciwuci** [comment]
same here

**Comment by Duciwuci** [comment]
Are you using a conda enviroment?

**Comment by vaibhavsethia** [comment]
pip

**Comment by vaibhavsethia** [comment]
No, I'm using Pip with Pycharm

**Comment by Duciwuci** [comment]
[#30 ](https://github.com/OlafenwaMoses/ImageAI/issues/30) for a workaround see this discussion. But I got the same issue on my conda enviroment and also tried with virtualenv. Installing all packages globally didn't fix the issue as well.
