### ISSUE TITLE
ValueError: You have specified an incorrect path to the ResNet model file.

### ISSUE THREAD

**Issue by sunwonkang** [OlafenwaMoses/ImageAI#462]
I tried to refer to other issue but could not resolve the error.
This is part of my code. (line23~line27)

`prediction = CustomImagePrediction()
prediction.setModelTypeAsResNet()
prediction.setModelPath(os.path.join(execution_path+ "idenprof_061-0.7933.h5"))
prediction.setJsonPath(os.path.join(execution_path+ "model_class.json"))
prediction.loadModel(num_objects=5)`

and Traceback

Traceback (most recent call last):
  File "D:\project\ImageAI_test\imageai\Prediction\Custom\__init__.py", line 487, in loadModel
    model = ResNet50(model_path=self.modelPath, weights="trained", model_input=image_input, num_classes=self.numObjects)
  File "D:\project\ImageAI_test\imageai\Prediction\ResNet\resnet50.py", line 119, in ResNet50
    model.load_weights(weights_path)
  File "C:\Users\S\Miniconda3\envs\ImageAi\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py", line 1093, in load_weights
    f = h5py.File(filepath, mode='r')
  File "C:\Users\S\Miniconda3\envs\ImageAi\lib\site-packages\h5py\_hl\files.py", line 408, in __init__
    swmr=swmr)
  File "C:\Users\S\Miniconda3\envs\ImageAi\lib\site-packages\h5py\_hl\files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'D:/project/ImageAI_test/kneeKL299idenprof_061-0.7933.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 27, in <module>
    prediction.loadModel(num_objects=5)
  File "D:\project\ImageAI_test\imageai\Prediction\Custom\__init__.py", line 491, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.

**Comment by AbimbolaOO** [comment]
Hello @sunwonkang,
I think an easy way to resolve this is to use relative paths i.e copy the model and JSON file to the same folder where the code you are running then do what is written below.

prediction.setModelPath("idenprof_061-0.7933.h5") 
prediction.setJsonPath("model_class.json"))

**Comment by ashucode** [comment]
hello @AbimbolaOO 

> Hello @sunwonkang,
> I think an easy way to resolve this is to use relative paths i.e copy the model and JSON file to the same folder where the code you are running then do what is written below.
> 
> prediction.setModelPath("idenprof_061-0.7933.h5")
> prediction.setJsonPath("model_class.json"))

my issue is not solving despite of this, model path for resnet is not being accepted
