### ISSUE TITLE
KeyError: 'xmax'

### ISSUE THREAD

**Issue by SuryaKumaryeditha** [OlafenwaMoses/ImageAI#482]
Using TensorFlow backend.
Generating anchor boxes for training images and annotation...
Traceback (most recent call last):
  File "C:\TCS project\train.py", line 6, in <module>
    trainer.setTrainConfig(object_names_array=["airport"], batch_size=4, num_experiments=10, train_from_pretrained_model="pretrained-yolov3.h5")
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python36\lib\site-packages\imageai\Detection\Custom\__init__.py", line 171, in setTrainConfig
    self.__train_cache_file, self.__model_labels)
  File "C:\Users\pavan\AppData\Local\Programs\Python\Python36\lib\site-packages\imageai\Detection\Custom\gen_anchors.py", line 90, in generateAnchors
    relative_w = (float(obj['xmax']) - float(obj['xmin']))/image['width']
KeyError: 'xmax'

unable to debug the error.Help required

**Comment by SuryaKumaryeditha** [comment]
solved it by creating new annotations.
