### ISSUE TITLE
 object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by hanotrahul** [OlafenwaMoses/ImageAI#499]
When I start training for more than 1 labels it shows an error as
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/deploy/rahul_vir/venv/lib/python3.5/site-packages/imageai/Detection/Custom/__init__.py", line 233, in trainModel
    norm=normalize
  File "/home/deploy/rahul_vir/venv/lib/python3.5/site-packages/imageai/Detection/Custom/generator.py", line 36, in __init__
    if shuffle: np.random.shuffle(self.instances)
  File "mtrand.pyx", line 4417, in numpy.random.mtrand.RandomState.shuffle
TypeError: object of type 'NoneType' has no len()

code:------------------------------------------------
from imageai.Detection.Custom import DetectionModelTrainer

trainer = DetectionModelTrainer()
trainer.setModelTypeAsYOLOv3()
trainer.setDataDirectory(data_directory="hololens")
 trainer.setTrainConfig( ["hololens", "google-glass", "oculus"], batch_size=2, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")

**Comment by heisen273** [comment]
How did you fix it?
