### ISSUE TITLE
ValueError: 'oculus' is not in list

### ISSUE THREAD

**Issue by rashminair1986** [OlafenwaMoses/ImageAI#516]
Epoch 1/100
Traceback (most recent call last):
  File "hololens_train.py", line 7, in <module>
    trainer.trainModel()
  File "D:\deeplearningvideos\anaconda\lib\site-packages\imageai\Detection\Custom\__init__.py", line 291, in trainModel
    max_queue_size=8
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\engine\training_generator.py", line 185, in fit_generator
    generator_output = next(output_generator)
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\utils\data_utils.py", line 625, in get
    six.reraise(*sys.exc_info())
  File "D:\deeplearningvideos\anaconda\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\utils\data_utils.py", line 610, in get
    inputs = future.get(timeout=30)
  File "D:\deeplearningvideos\anaconda\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
  File "D:\deeplearningvideos\anaconda\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\deeplearningvideos\anaconda\lib\site-packages\keras\utils\data_utils.py", line 406, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "D:\deeplearningvideos\anaconda\lib\site-packages\imageai\Detection\Custom\generator.py", line 112, in __getitem__
    obj_indx = self.labels.index(obj['name'])
ValueError: 'oculus' is not in list

**Comment by rashminair1986** [comment]
i could resolve it... no issues now 
just added 
trainer.setTrainConfig(object_names_array=["hololens","oculus"], batch_size=4, num_experiments=100, train_from_pretrained_model="pretrained-yolov3.h5")
