### ISSUE TITLE
Error that cudart64_101.dll not found

### ISSUE THREAD

**Issue by hsiehstyle** [OlafenwaMoses/ImageAI#561]
When I try to run the program, it says could not load the dynamic library 'cudar64_101.dll.' Does anyone run into this issue? Thank you! I'm running on Windows 10 with GTX 1080Ti.

2020-07-14 14:16:22.487909: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-07-14 14:16:22.488088: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\Kevin\Downloads\Python\Stanford Continuing Study 2020\Lecture 3\Computer vision\FirstPrediction.py", line 18, in run
    prediction.loadModel()
UnboundLocalError: local variable 'prediction' referenced before assignment
[Finished in 2.6s]

**Comment by AbimbolaOO** [comment]
Hello @hsiehstyle,

Please make sure you are not running **tensorflow 2.1.0 or python 3.7.6**. check your python version by running **python3 --version** and to check your TensorFlow version run **print(tf.__version__)** in python. After confirming your python version and TensorFlow version and they are not any of the versions listed below please reinstall them to the version listed below. 

python3.6
pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if you are using a GPU

Then install the following software and you would be read to go
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade

**Comment by alexresiga** [comment]
Based on your error message, you need to download the cuda toolkit specific to that version, that is given by _101.dll. This means you need to download CUDA Toolkit 10.1 from [here](https://developer.nvidia.com/cuda-10.1-download-archive-base?target_os=Windows&target_arch=x86_64&target_version=10).

**Comment by hsiehstyle** [comment]
Hi Alex and Olaymei,

I have tried to reinstall the below items:

1.

python3.6
pip install tensorflow==1.13.1 or pip3 install tensorflow-gpu==1.13.1 if
you are using a GPU

Then install the following software and you would be read to go
pip install keras==2.2.4
pip install numpy==1.16.1
pip install opencv-python
pip install imageai --upgrade
2.
 download CUDA Toolkit 10.1 from here
<https://developer.nvidia.com/cuda-10.1-download-archive-base?target_os=Windows&target_arch=x86_64&target_version=10>
.

When I tried to run the ImagePrediction.py file, this screenshot is what I
saw. Please advise if it was correct or not. Thank you.

[image: image.png]

**Comment by alexresiga** [comment]
i cannot see the attached image @hsiehstyle
