### ISSUE TITLE
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 

### ISSUE THREAD

**Issue by lkoll** [OlafenwaMoses/ImageAI#583]
I am seeing this error all over with no consistent fix... I have my image, model and python file all saved in the current working directory. The only thing different than the tutorial example is I'm doing the detection on an image on my computer. I have tried them as both .jpeg and .png. I know I've seen people say there is a lot of possible options because of how the try catch is structured, but are there other things I can do?

```
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()

detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "01235.jpeg"), output_image_path=os.path.join(execution_path , "01235_2.jpeg"))

for eachObject in detections:
    print(eachObject["name"] , " : " , eachObject["percentage_probability"] )
```

Full error traceback
```
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "01235.jpeg"), output_image_path=os.path.join(execution_path , "01235_2.jpeg"))
Traceback (most recent call last):

  File "C:\Users\Luke\anaconda3\lib\site-packages\imageai\Detection\__init__.py", line 347, in detectObjectsFromImage
    _, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\engine\training.py", line 1274, in predict_on_batch
    outputs = self.predict_function(ins)

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)

  File "C:\Users\Luke\anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)

  File "C:\Users\Luke\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)

UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
	 [[nms/GatherNd_76/_1851]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
0 successful operations.
0 derived errors ignored.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "<ipython-input-8-5b2861cc813f>", line 1, in <module>
    detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "01235.jpeg"), output_image_path=os.path.join(execution_path , "01235_2.jpeg"))

  File "C:\Users\Luke\anaconda3\lib\site-packages\imageai\Detection\__init__.py", line 544, in detectObjectsFromImage
    "Ensure you specified correct input image, input type, output type and/or output image path ")

ValueError: Ensure you specified correct input image, input type, output type and/or output image path 
```

**Comment by Thanossrs** [comment]
I have the same problem.
please, everyone!

**Comment by Danzo0l** [comment]
ПАМАГИТЕ!!!!!! HELP! HELP ME!

**Comment by Zordiac** [comment]
Read the error message, It says cuDNN failed to initialize. Have you installed the correct version of cudnn?

**Comment by liusui652** [comment]
I have the same problem.I tested successfully on Google colab, but I kept reporting errors on pycharm and vscode.Pray for help, thank you very much in advance！！！！
ValueError: Ensure you specified correct input image, input type, output type and/or output image path 

Full error traceback：
"D:\Program File\Anaconda3\envs\tensorflow-gpu\python.exe" F:/PYcharm/yolo/object_detection.py
Using TensorFlow backend.
2020-11-11 16:41:14.560524: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-11 16:41:16.701787: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-11-11 16:41:17.665907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce MX350 major: 6 minor: 1 memoryClockRate(GHz): 1.468
pciBusID: 0000:02:00.0
2020-11-11 16:41:17.666102: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-11 16:41:17.669014: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-11-11 16:41:17.671949: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-11-11 16:41:17.673215: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-11-11 16:41:17.677234: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-11-11 16:41:17.679997: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-11-11 16:41:17.688575: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-11-11 16:41:17.689202: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-11-11 16:41:17.689656: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-11-11 16:41:17.692760: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties: 
name: GeForce MX350 major: 6 minor: 1 memoryClockRate(GHz): 1.468
pciBusID: 0000:02:00.0
2020-11-11 16:41:17.692973: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-11-11 16:41:17.693113: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2020-11-11 16:41:17.693251: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2020-11-11 16:41:17.693393: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2020-11-11 16:41:17.693536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2020-11-11 16:41:17.693677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2020-11-11 16:41:17.693843: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-11-11 16:41:17.694426: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2020-11-11 16:41:18.566317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-11 16:41:18.566466: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0 
2020-11-11 16:41:18.566554: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N 
2020-11-11 16:41:18.567378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 1343 MB memory) -> physical GPU (device: 0, name: GeForce MX350, pci bus id: 0000:02:00.0, compute capability: 6.1)
WARNING:tensorflow:From D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
WARNING:tensorflow:From D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\backend\tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\imageai\Detection\keras_retinanet\backend\tensorflow_backend.py:22: The name tf.image.resize_images is deprecated. Please use tf.image.resize instead.

tracking <tf.Variable 'Variable:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_1:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_2:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_3:0' shape=(9, 4) dtype=float32> anchors
tracking <tf.Variable 'Variable_4:0' shape=(9, 4) dtype=float32> anchors
WARNING:tensorflow:From D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\imageai\Detection\keras_retinanet\backend\tensorflow_backend.py:46: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\backend\tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

2020-11-11 16:41:33.939478: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2020-11-11 16:41:35.774044: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
2020-11-11 16:41:35.777809: E tensorflow/stream_executor/cuda/cuda_dnn.cc:319] Loaded runtime CuDNN library: 7.4.1 but source was compiled with: 7.6.0.  CuDNN library major and minor version needs to match or have higher minor version in case of CuDNN 7.0 or later version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
Traceback (most recent call last):
  File "D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\imageai\Detection\__init__.py", line 347, in detectObjectsFromImage
    _, _, detections = model.predict_on_batch(np.expand_dims(image, axis=0))
  File "D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\keras\engine\training.py", line 1580, in predict_on_batch
    outputs = self.predict_function(ins)
  File "D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\keras\backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow_core\python\client\session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.UnknownError: 2 root error(s) found.
  (0) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
	 [[classification/concat/_1845]]
  (1) Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv1/convolution}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/PYcharm/yolo/object_detection.py", line 10, in <module>
    detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "2.jpg"), output_image_path=os.path.join(execution_path , "2_detected.png"), extract_detected_objects = True, minimum_percentage_probability=40)
  File "D:\Program File\Anaconda3\envs\tensorflow-gpu\lib\site-packages\imageai\Detection\__init__.py", line 544, in detectObjectsFromImage
    "Ensure you specified correct input image, input type, output type and/or output image path ")
ValueError: Ensure you specified correct input image, input type, output type and/or output image path

**Comment by liusui652** [comment]
I have the same problem.I tested successfully on Google colab, but I kept reporting errors on pycharm and vscode.Pray for help, thank you very much in advance！！！！
ValueError: Ensure you specified correct input image, input type, output type and/or output image path
Full error traceback：

![image](https://user-images.githubusercontent.com/62026472/98789644-881ae100-243d-11eb-943a-c976d6ed5a42.png)

**Comment by Zordiac** [comment]
Update cuDNN to 7.6
