### ISSUE TITLE
AttributeError: module 'keras.backend' has no attribute 'get_session'

### ISSUE THREAD

**Issue by GetRektBoy724** [OlafenwaMoses/ImageAI#596]
I run an example code from ImageAI
and its showed up something like this : 
`
Traceback (most recent call last):
  File "./camera_feed_detection.py", line 10, in <module>
    detector = VideoObjectDetection()
  File "/usr/local/lib/python3.8/dist-packages/imageai/Detection/__init__.py", line 984, in __init__
    self.sess = K.get_session()
AttributeError: module 'keras.backend' has no attribute 'get_session'
`
i use tensorflow non-avx build version 2.4.0
i get it in here : https://github.com/yaroslavvb/tensorflow-community-wheels/issues/158
i already test the tensorflow and its working
pls tell me if you want more information
pls help...any answer is appreciated :D

**Comment by GetRektBoy724** [comment]
lmao i bypass the problem (kinda tho)
i modified the code to
`
...
from imageai.Detection import VideoObjectDetection as detector
...
`
