### ISSUE TITLE
Linux-only issue: "ValueError: You have specified an incorrect path to the ResNet model file."

### ISSUE THREAD

**Issue by TheNewJavaman** [OlafenwaMoses/ImageAI#598]
I cloned all of my files directly from a Windows 10 machine to my Raspberry Pi. After verifying that I installed the right dependencies, I get this error: 

```
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/imageai/Prediction/Custom/__init__.py", line 487, in loadModel
    model = ResNet50(model_path=self.modelPath, weights="trained", model_input=image_input, num_classes=self.numObjects)
  File "/usr/local/lib/python3.7/dist-packages/imageai/Prediction/ResNet/resnet50.py", line 119, in ResNet50
    model.load_weights(weights_path)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/training.py", line 224, in load_weights
    return super(Model, self).load_weights(filepath, by_name, skip_mismatch)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/engine/network.py", line 1200, in load_weights
    saving.load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python3.7/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 651, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 38, in <module>
    predictor = Predictor("model_ex-067_acc-0.953125.h5")
  File "app.py", line 26, in __init__
    self.prediction.loadModel(num_objects=3)
  File "/usr/local/lib/python3.7/dist-packages/imageai/Prediction/Custom/__init__.py", line 491, in loadModel
    raise ValueError("You have specified an incorrect path to the ResNet model file.")
ValueError: You have specified an incorrect path to the ResNet model file.
```

Once again, I changed absolutely no source code; the only change was the OS. I verified that every file was the same with SHA256 checksums.

**Comment by TheNewJavaman** [comment]
To provide a little more context: I created a CustomPrediction model and am using it fine on Windows. I decided to make a smaller, dedicated server on a Raspberry Pi. You can see all my source code for the Prediction class [here](https://github.com/masquitowastaken/masquito-backend) in `app.py`

**Comment by TheNewJavaman** [comment]
Update: had to fix some inconsistent package versions using pip. Guide on [StackOverflow](https://stackoverflow.com/questions/64640117/imageai-keras-cant-read-resnet-model-on-raspberry-pi-but-works-on-windows/64650664#64650664)
