### ISSUE TITLE
tkinter causes CustomObjectDetection module import failure in Google Cloud Function

### ISSUE THREAD

**Issue by LOActualControl** [OlafenwaMoses/ImageAI#803]
Good afternoon,

I'm trying to upload a trained Custom Object Detection model to Google Cloud Storage and run inference using a Cloud Function. However, when I upload my function to the Google Cloud Platform, importing the CustomObjectDetection module fails. I think this is because one of the required packages is tkinter, which might not work in a cloud/headless platform? But I can't figure out why tkinter/a GUI would be required for imageai. Any help toward resolving this would be greatly appreciated! My code and the full stack trace of my error is below:

`import numpy as np
from imageai.Detection.Custom import CustomObjectDetection

def  predict(self):
  return "hello world"`

Deployment failure:
Function failed on loading user code. This is likely due to a bug in the user code. Error message: Traceback (most recent call last):
File "/layers/google.python.pip/pip/bin/functions-framework", line 8, in <module>
sys.exit(_cli())
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
return self.main(*args, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1053, in main
rv = self.invoke(ctx)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/click/core.py", line 754, in invoke
return __callback(*args, **kwargs)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/_cli.py", line 37, in _cli
app = create_app(target, source, signature_type)
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/functions_framework/__init__.py", line 288, in create_app
spec.loader.exec_module(source_module)
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/workspace/main.py", line 2, in <module>
from imageai.Detection.Custom import CustomObjectDetection
File "/layers/google.python.pip/pip/lib/python3.9/site-packages/imageai/Detection/__init__.py", line 2, in <module>
from tkinter import Image
File "/layers/google.python.runtime/python/lib/python3.9/tkinter/__init__.py", line 37, in <module>
import _tkinter # If this fails your Python may not be configured for Tk
ImportError: libBLT.2.5.so.8.6: cannot open shared object file: No such file or directory
. Please visit https://cloud.google.com/functions/docs/troubleshooting for in-depth troubleshooting documentation.

**Comment by LOActualControl** [comment]
Yeah I noticed the same thing too @EdwinAguirre92 ! In fact, I assume the rest of the Image references in the functions/classes that follow are from the PIL import, rather than the tkinter import. Perhaps tkinter isn't necessary after all - I ended up actually using a different package than ImageAI for my current project, but removing tkinter could be helpful for future projects.

**Comment by azamikram** [comment]
Any updates on this? I am facing the same issue on AWS Lambda.

**Comment by elmackico93** [comment]
To resolve the issue with ImageAI and make the object detection scalable, efficient, and cloud-compatible, replace CustomObjectDetection with a streamlined TensorFlow-based YOLO implementation:
import tensorflow as tf
import numpy as np
import cv2

def run_detection(image_path, model_path, output_path):
    # Load YOLO model dynamically
    model = tf.keras.models.load_model(model_path)

    # Preprocess image
    image = cv2.imread(image_path)
    input_image = cv2.resize(image, (416, 416)) / 255.0
    input_image = np.expand_dims(input_image, axis=0)

    # Run inference
    predictions = model.predict(input_image)

    # Post-process predictions and annotate image
    detections = postprocess_predictions(predictions, image.shape)
    annotate_image(image, detections, output_path)

def postprocess_predictions(predictions, original_shape):
    # Parse YOLO output and scale to original dimensions (pseudo-code)
    return [{"box": [10, 20, 100, 120], "confidence": 0.95, "class": 1}]

def annotate_image(image, detections, output_path):
    for detection in detections:
        x1, y1, x2, y2 = detection["box"]
        cv2.rectangle(image, (x1, y1), (x2, y2), (0, 255, 0), 2)
    cv2.imwrite(output_path, image)
    	•	Advantages:
	•	Lightweight TensorFlow YOLO pipeline with no Tkinter dependency.
	•	Headless-friendly for cloud environments like Google Cloud Functions.
	•	Scalable and compact for real-world deployments.

Replace the old ObjectDetection block with:
run_detection("/tmp/input.jpg", "/tmp/yolo.h5", "/tmp/output.jpg")
Let me know if you need further assistance! 😄

**Comment by elmackico93** [comment]
What kind of device are you using?

**Comment by elmackico93** [comment]
https://github.com/user-attachments/assets/ab7b1ae0-703c-40b5-be65-ef42f6f076f2
