### ISSUE TITLE
SystemError: <built-in function AppendFloat32ArrayToTensorProto> returned NULL without setting an error

### ISSUE THREAD

**Issue by varunajmera0** [OlafenwaMoses/ImageAI#83]
Using TensorFlow backend.
/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
2018-09-30 17:54:47.967465: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.2 AVX
Traceback (most recent call last):
  File "imaged.py", line 9, in <module>
    detector.loadModel()
  File "/usr/local/lib/python3.7/site-packages/imageai/Detection/__init__.py", line 189, in loadModel
    model = yolo_main(Input(shape=(None, None, 3)), len(self.__yolo_anchors) // 3, len(self.numbers_to_names))
  File "/usr/local/lib/python3.7/site-packages/imageai/Detection/YOLOv3/models.py", line 60, in yolo_main
    darknet_network = Model(input, darknet(input))
  File "/usr/local/lib/python3.7/site-packages/imageai/Detection/YOLOv3/models.py", line 33, in darknet
    network = NetworkConv2D_BN_Leaky(input=input, channels=32, kernel_size=(3,3))
  File "/usr/local/lib/python3.7/site-packages/imageai/Detection/YOLOv3/models.py", line 16, in NetworkConv2D_BN_Leaky
    network = Conv2D( filters=channels, kernel_size=kernel_size, strides=strides, padding=padding, kernel_regularizer=kernel_regularizer, use_bias=use_bias)(input)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/topology.py", line 576, in __call__
    self.build(input_shapes[0])
  File "/usr/local/lib/python3.7/site-packages/keras/layers/convolutional.py", line 134, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/topology.py", line 397, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python3.7/site-packages/keras/initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 3637, in random_uniform
    dtype=dtype, seed=seed)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/ops/random_ops.py", line 232, in random_uniform
    minval = ops.convert_to_tensor(minval, dtype=dtype, name="min")
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 932, in convert_to_tensor
    as_ref=False)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 233, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 212, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 513, in make_tensor_proto
    append_fn(tensor_proto, proto_values)
SystemError: <built-in function AppendFloat32ArrayToTensorProto> returned NULL without setting an error

**Comment by OlafenwaMoses** [comment]
Kindly uninstall the Tensorflow version you have installed and instead install tensorflow version 1.5.0 using the pip command below.

pip3 install tensorflow==1.5.0
