### ISSUE TITLE
Detection using custom model

### ISSUE THREAD

**Issue by John-Almardeny** [OlafenwaMoses/ImageAI#84]
I am getting this error:
```
Traceback (most recent call last):
  File "/home/yahya/Desktop/ML/FirstDetection.py", line 11, in <module>
    detector.loadModel()
  File "/usr/local/lib/python3.5/dist-packages/imageai/Detection/__init__.py", line 185, in loadModel
    model.load_weights(self.modelPath)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1166, in load_weights
    f, self.layers, reshape=reshape)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/saving.py", line 1030, in load_weights_from_hdf5_group
    str(len(filtered_layers)) + ' layers.')
ValueError: You are trying to load a weight file containing 107 layers into a model with 116 layers.
```

My code is as simple as this:

```
from imageai.Detection import ObjectDetection
import os

execution_path = os.getcwd()
detector = ObjectDetection()
detector.setModelTypeAsRetinaNet()
detector.setModelPath(os.path.join(execution_path , "custom_model.h5"))
detector.loadModel()
detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "2.png"))
```

**Comment by John-Almardeny** [comment]
Thanks. That makes sense now.

**Comment by rw86347** [comment]
I just realized this too.  Do you have a time frame for when detection will be supported?

**Comment by OlafenwaMoses** [comment]
Please refer to #8
