### ISSUE TITLE
ImportError: No module named 'tensorflow.python'

### ISSUE THREAD

**Issue by wassimgoodar** [OlafenwaMoses/ImageAI#91]
Hi
i have tested the object detection using tenserflow for cpu and it is working fine and it is taking between 15 to 25 seconds to do object detection using tiny-yolo.
However, when i try to test it using tenserflow GPU using Nvidea Getfoce GTX 950M, i am getting the following error.Can anyone help me please??
i have install tensorflow gpu using the command pip install tensorflow-gpu and has successfully installed 
 tensorflow gpu version 1.11.0

 C:\Users\acer\PycharmProjects\imageai\venv\Scripts\python.exe C:/Users/acer/PycharmProjects/imageai/firstdetectiongpu.py
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/acer/PycharmProjects/imageai/firstdetectiongpu.py", line 1, in <module>
    from imageai.Detection import ObjectDetection
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\imageai\Detection\__init__.py", line 3, in <module>
    from imageai.Detection.keras_retinanet.models.resnet import resnet50_retinanet
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\imageai\Detection\keras_retinanet\models\resnet.py", line 19, in <module>
    import keras
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\keras\__init__.py", line 3, in <module>
    from . import utils
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\keras\utils\__init__.py", line 6, in <module>
    from . import conv_utils
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\keras\utils\conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\keras\backend\__init__.py", line 89, in <module>
    from .tensorflow_backend import *
  File "C:\Users\acer\PycharmProjects\imageai\venv\lib\site-packages\keras\backend\tensorflow_backend.py", line 6, in <module>
    from tensorflow.python.framework import ops as tf_ops
ImportError: No module named 'tensorflow.python'

Process finished with exit code 1

**Comment by wassimgoodar** [comment]
i had wrongly installled tensorflow-gpu dependencies like cuda, cudnn
